import { LightningElement, api, wire } from 'lwc';
import { getRecord } from 'lightning/uiRecordApi';
import CASE_NUMBER_FIELD from '@salesforce/schema/Case.CaseNumber';
import LightningConfirm from 'lightning/confirm';


import getActivationLinesAllProducts from '@salesforce/apex/ActivationLineExportController.getActivationLinesAllProducts';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';

export default class ActivationLineExportTool extends LightningElement {
    @api recordId; // Current Case record ID
    @api objectApiName; // API name of the triggering object (e.g., 'Case')
    @api fields = `
    Product__c,
    Quote_line__c,
    Phone_no__c,
    First_name__c,
    Last_name__c,
    Phone_no_Status__c,
    Mobile_no__c,
    Telia_INSIGHT_e_mail_contact__c,
    SIM_number__c,
    Not_to_Activation__c,
    Operator__c,
    Sales_type__c,
    Power_of_Attorney_record__c,
    Planned_delivery_date__c,
    Number_Porting_Specific_Date__c,
    Modified_delivery_date__c,
    Number_Porting_End_of_Commitment__c,
    Existing_SIM_number__c,
    Related_Activation_line__c,
    Telia_til_Telia_transfer__c,
    UC_Invoicing__c,
    Number_Series_Main_Number__c,
    Show_On_Onboarding_Page__c,
    Onboarding_Activation_Line__c,
    Escalated__c,
    VAS_CORDKTEU4__c,
    VAS_SIMBTB11__c,
    VAS_CORDKTEU5__c,
    Ekstra_Data_SIM_number__c,
    VAS_CORDKTOEU__c,
    VAS_SIMBX5__c,
    VAS_CORWA10G__c,
    Ekstra_Data_SIM_number_2__c,
    VAS_CORWA5G__c,
    VAS_SIMBX6__c,
    VAS_CORWB8G__c,
    Ekstra_Data_SIM_number_3__c,
    VAS_CORWA9G__c,
    VAS_SIMBX7__c,
    VAS_CORUSA5G__c,
    Ekstra_Data_SIM_number_4__c,
    VAS_CORAS5G__c,
    VAS_DUMMY2__c,
    VAS_ALLBIZA__c,
    VAS_TMSBBAND__c,
    VAS_FIX2MOBIL__c,
    VAS_TMSMOBILE__c,
    VAS_EntitleAW__c,
    VAS_M2MROAM__c,
    VAS_M2M_Data__c,
    VAS_M2M_SMS__c,
    Funktionsnr__c,
    Touchpoint_Statistik__c,
    Touchpoint_Bruger__c,
    Touchpoint_Softphone__c,
    Touchpoint_Receptionist__c,
    VAS_UC_License__c,
    Email__c,
    Shortnr__c,
    Department__c,
    Administrator__c,
    Job_description__c,
    Supervisor__c,
    Locale__c,
    Attendant_Agent_login__c,
    Keywords__c,
    VAS_TPXRECB__c,
    VAS_TPXREC3__c,
    VAS_TPXREC7__c,
    Fastnet_no_Type__c,
    Wallboard__c,
    Fax__c,
    Conference__c,
    Extra_ACD_k__c,
    Statistics__c,
    Extra_ACD_k_Quantity__c,
    Single_No__c,
    Supervisor_No__c,
    X70_80_nummer__c,
    Attendant_Agent_login_No__c,
    TPX_Deskphone__c,
    TPX_Power_Adapter__c,
    VAS_OCMUSR__c,
    VAS_FINTDKEU__c,
    VAS_OCCATTCON__c,
    VAS_OCCONB__c,
    VAS_OCCOFFCLI__c,
    VAS_OCCAAO__c,
    VAS_OCCCCENTV__c,
    VAS_OCCAAS__c,
    VAS_OCCCCWGRV__c,
    VAS_OCCAAU__c,
    VAS_OCCMOBPGW__c,
    VAS_OCCBAS__c,
    VAS_OCCIVREXP__c,
    VAS_OCCASO__c,
    VAS_OCCCLBACK__c,
    VAS_OCCCON__c,
    VAS_OCCQUAMON__c,
    VAS_OCCINS__c,
    VAS_OCCCCENTM__c,
    VAS_OCCCCWGRM__c,
    VAS_OCCCRMINT__c,
    VAS_OCCMAILDI__c,
    VAS_OCCAVAIVA__c,
    VAS_OCCSCSTAT__c,
    VAS_OCCAGRECO__c,
    VAS_BAR3G__c,
    VAS_BARPRCSMS__c,
    VAS_BAR4G__c,
    VAS_BAR90__c,
    VAS_BARDATA__c,
    VAS_BARORXD__c,
    VAS_BARINTRO__c,
    VAS_BAROUTRO__c,
    VAS_BARMMS__c,
    VAS_BARINTCAL__c,
    VAS_BARTOTRO__c,
    VAS_BARSTD__c,
    VAS_BARLEVEL__c,
    Forbrugskontrol_amount__c,
    VAS_BARINC__c,
    VAS_BARTOTAL__c,
    VAS_BAROUTG__c,
    RCC_Owner_Control__c,
    VAS_BARINCRO__c,
    TSRR_Owner_Control__c,
    NUA_Owner_Control__c,
    VAS_TSPBRONZE__c,
    VAS_TSPSOLV__c,
    VAS_TSPGULD__c,
    Billing_Account__c,
    Billing_Account_Number__c,
    Invoice_Type_F__c,
    Invoice_Email_F__c,
    Company_Name__c,
    EAN_number_F__c,
    Delivery_Att__c,
    Billing_Att_F__c,
    Delivery_Street_and_number__c,
    Billing_Name_F__c,
    Delivery_City__c,
    Billing_Street_and_No_F__c,
    Postal_Code__c,
    Billing_Postal_Code_F__c,
    Delivery_Country__c,
    Billing_City_F__c,
    Delivery_Email__c,
    Billing_Country_F__c`;
   @api activationLines = []; // Holds the fetched Activation Lines
    caseNumber; // To store the CaseNumber

    // Define the fields to fetch
    static FIELDS = [CASE_NUMBER_FIELD];

    // Wire the Case record
    @wire(getRecord, { recordId: '$recordId', fields: ActivationLineExportTool.FIELDS })
    wiredCase({ error, data }) {
        if (data) {
            this.caseNumber = data.fields.CaseNumber.value; // Extract CaseNumber
        } else if (error) {
            console.error('Error fetching Case record:', error);
        }
    }
    @api async invoke() {
        const result = await LightningConfirm.open({
            label: 'Confirmation',
            theme: 'warning',
            message: 'By exporting this data, you acknowledge you are responsible for ensuring compliance with GDPR and other applicable data protection regulations. The exported data should only be used for its intended purpose and must be deleted once you are done working with it to prevent unauthorized access or misuse.',
        });
        if (result) {
            this.handleConfirm(); // Proceed with the confirm logic
        } else {
            console.log('Export canceled.');
        }
    }

    

   @api async handleConfirm() {
        console.log('Invoke method called in ActivationLineExportTool.');
        try {
            const data = await getActivationLinesAllProducts({ caseId: this.recordId });
            if (!data || data.length === 0) {
                this.showToast('No Data', 'No Activation Lines found for this Case.', 'info');
                return;
            }

            this.activationLines = data.map(record => ({
                Product__c: record.Product__c || '',
                Quote_line__c: record.Quote_line__c || '',
                Phone_no__c: record.Phone_no__c || '',
                First_name__c: record.First_name__c || '',
                Last_name__c: record.Last_name__c || '',
                Phone_no_Status__c: record.Phone_no_Status__c || '',
                Mobile_no__c: record.Mobile_no__c || '',
                Telia_INSIGHT_e_mail_contact__c: record.Telia_INSIGHT_e_mail_contact__c || '',
                SIM_number__c: record.SIM_number__c || '',
                Not_to_Activation__c: record.Not_to_Activation__c || '',
                Operator__c: record.Operator__c || '',
                Sales_type__c: record.Sales_type__c || '',
                Power_of_Attorney_record__c: record.Power_of_Attorney_record__c || '',
                Planned_delivery_date__c: record.Planned_delivery_date__c || '',
                Number_Porting_Specific_Date__c: record.Number_Porting_Specific_Date__c || '',
                Modified_delivery_date__c: record.Modified_delivery_date__c || '',
                Number_Porting_End_of_Commitment__c: record.Number_Porting_End_of_Commitment__c || '',
                Existing_SIM_number__c: record.Existing_SIM_number__c || '',
                Related_Activation_line__c: record.Related_Activation_line__c || '',
                Telia_til_Telia_transfer__c: record.Telia_til_Telia_transfer__c || '',
                UC_Invoicing__c: record.UC_Invoicing__c || '',
                Number_Series_Main_Number__c: record.Number_Series_Main_Number__c || '',
                Show_On_Onboarding_Page__c: record.Show_On_Onboarding_Page__c || '',
                Onboarding_Activation_Line__c: record.Onboarding_Activation_Line__c || '',
                Escalated__c: record.Escalated__c || '',
                VAS_CORDKTEU4__c: record.VAS_CORDKTEU4__c || '',
                VAS_SIMBTB11__c: record.VAS_SIMBTB11__c || '',
                VAS_CORDKTEU5__c: record.VAS_CORDKTEU5__c || '',
                Ekstra_Data_SIM_number__c: record.Ekstra_Data_SIM_number__c || '',
                VAS_CORDKTOEU__c: record.VAS_CORDKTOEU__c || '',
                VAS_SIMBX5__c: record.VAS_SIMBX5__c || '',
                VAS_CORWA10G__c: record.VAS_CORWA10G__c || '',
                Ekstra_Data_SIM_number_2__c: record.Ekstra_Data_SIM_number_2__c || '',
                VAS_CORWA5G__c: record.VAS_CORWA5G__c || '',
                VAS_SIMBX6__c: record.VAS_SIMBX6__c || '',
                VAS_CORWB8G__c: record.VAS_CORWB8G__c || '',
                Ekstra_Data_SIM_number_3__c: record.Ekstra_Data_SIM_number_3__c || '',
                VAS_CORWA9G__c: record.VAS_CORWA9G__c || '',
                VAS_SIMBX7__c: record.VAS_SIMBX7__c || '',
                VAS_CORUSA5G__c: record.VAS_CORUSA5G__c || '',
                Ekstra_Data_SIM_number_4__c: record.Ekstra_Data_SIM_number_4__c || '',
                VAS_CORAS5G__c: record.VAS_CORAS5G__c || '',
                VAS_DUMMY2__c: record.VAS_DUMMY2__c || '',
                VAS_ALLBIZA__c: record.VAS_ALLBIZA__c || '',
                VAS_TMSBBAND__c: record.VAS_TMSBBAND__c || '',
                VAS_FIX2MOBIL__c: record.VAS_FIX2MOBIL__c || '',
                VAS_TMSMOBILE__c: record.VAS_TMSMOBILE__c || '',
                VAS_EntitleAW__c: record.VAS_EntitleAW__c || '',
                VAS_M2MROAM__c: record.VAS_M2MROAM__c || '',
                VAS_M2M_Data__c: record.VAS_M2M_Data__c || '',
                VAS_M2M_SMS__c: record.VAS_M2M_SMS__c || '',
                Funktionsnr__c: record.Funktionsnr__c || '',
                Touchpoint_Statistik__c: record.Touchpoint_Statistik__c || '',
                Touchpoint_Bruger__c: record.Touchpoint_Bruger__c || '',
                Touchpoint_Softphone__c: record.Touchpoint_Softphone__c || '',
                Touchpoint_Receptionist__c: record.Touchpoint_Receptionist__c || '',
                VAS_UC_License__c: record.VAS_UC_License__c || '',
                Email__c: record.Email__c || '',
                Shortnr__c: record.Shortnr__c || '',
                Department__c: record.Department__c || '',
                Administrator__c: record.Administrator__c || '',
                Job_description__c: record.Job_description__c || '',
                Supervisor__c: record.Supervisor__c || '',
                Locale__c: record.Locale__c || '',
                Attendant_Agent_login__c: record.Attendant_Agent_login__c || '',
                Keywords__c: record.Keywords__c || '',
                VAS_TPXRECB__c: record.VAS_TPXRECB__c || '',
                VAS_TPXREC3__c: record.VAS_TPXREC3__c || '',
                VAS_TPXREC7__c: record.VAS_TPXREC7__c || '',
                Fastnet_no_Type__c: record.Fastnet_no_Type__c || '',
                Wallboard__c: record.Wallboard__c || '',
                Fax__c: record.Fax__c || '',
                Conference__c: record.Conference__c || '',
                Extra_ACD_k__c: record.Extra_ACD_k__c || '',
                Statistics__c: record.Statistics__c || '',
                Extra_ACD_k_Quantity__c: record.Extra_ACD_k_Quantity__c || '',
                Single_No__c: record.Single_No__c || '',
                Supervisor_No__c: record.Supervisor_No__c || '',
                X70_80_nummer__c: record.X70_80_nummer__c || '',
                Attendant_Agent_login_No__c: record.Attendant_Agent_login_No__c || '',
                TPX_Deskphone__c: record.TPX_Deskphone__c || '',
                TPX_Power_Adapter__c: record.TPX_Power_Adapter__c || '',
                VAS_OCMUSR__c: record.VAS_OCMUSR__c || '',
                VAS_FINTDKEU__c: record.VAS_FINTDKEU__c || '',
                VAS_OCCATTCON__c: record.VAS_OCCATTCON__c || '',
                VAS_OCCONB__c: record.VAS_OCCONB__c || '',
                VAS_OCCOFFCLI__c: record.VAS_OCCOFFCLI__c || '',
                VAS_OCCAAO__c: record.VAS_OCCAAO__c || '',
                VAS_OCCCCENTV__c: record.VAS_OCCCCENTV__c || '',
                VAS_OCCAAS__c: record.VAS_OCCAAS__c || '',
                VAS_OCCCCWGRV__c: record.VAS_OCCCCWGRV__c || '',
                VAS_OCCAAU__c: record.VAS_OCCAAU__c || '',
                VAS_OCCMOBPGW__c: record.VAS_OCCMOBPGW__c || '',
                VAS_OCCBAS__c: record.VAS_OCCBAS__c || '',
                VAS_OCCIVREXP__c: record.VAS_OCCIVREXP__c || '',
                VAS_OCCASO__c: record.VAS_OCCASO__c || '',
                VAS_OCCCLBACK__c: record.VAS_OCCCLBACK__c || '',
                VAS_OCCCON__c: record.VAS_OCCCON__c || '',
                VAS_OCCQUAMON__c: record.VAS_OCCQUAMON__c || '',
                VAS_OCCINS__c: record.VAS_OCCINS__c || '',
                VAS_OCCCCENTM__c: record.VAS_OCCCCENTM__c || '',
                VAS_OCCCCWGRM__c: record.VAS_OCCCCWGRM__c || '',
                VAS_OCCCRMINT__c: record.VAS_OCCCRMINT__c || '',
                VAS_OCCMAILDI__c: record.VAS_OCCMAILDI__c || '',
                VAS_OCCAVAIVA__c: record.VAS_OCCAVAIVA__c || '',
                VAS_OCCSCSTAT__c: record.VAS_OCCSCSTAT__c || '',
                VAS_OCCAGRECO__c: record.VAS_OCCAGRECO__c || '',
                VAS_BAR3G__c: record.VAS_BAR3G__c || '',
                VAS_BARPRCSMS__c: record.VAS_BARPRCSMS__c || '',
                VAS_BAR4G__c: record.VAS_BAR4G__c || '',
                VAS_BAR90__c: record.VAS_BAR90__c || '',
                VAS_BARDATA__c: record.VAS_BARDATA__c || '',
                VAS_BARORXD__c: record.VAS_BARORXD__c || '',
                VAS_BARINTRO__c: record.VAS_BARINTRO__c || '',
                VAS_BAROUTRO__c: record.VAS_BAROUTRO__c || '',
                VAS_BARMMS__c: record.VAS_BARMMS__c || '',
                VAS_BARINTCAL__c: record.VAS_BARINTCAL__c || '',
                VAS_BARTOTRO__c: record.VAS_BARTOTRO__c || '',
                VAS_BARSTD__c: record.VAS_BARSTD__c || '',
                VAS_BARLEVEL__c: record.VAS_BARLEVEL__c || '',
                Forbrugskontrol_amount__c: record.Forbrugskontrol_amount__c || '',
                VAS_BARINC__c: record.VAS_BARINC__c || '',
                VAS_BARTOTAL__c: record.VAS_BARTOTAL__c || '',
                VAS_BAROUTG__c: record.VAS_BAROUTG__c || '',
                RCC_Owner_Control__c: record.RCC_Owner_Control__c || '',
                VAS_BARINCRO__c: record.VAS_BARINCRO__c || '',
                TSRR_Owner_Control__c: record.TSRR_Owner_Control__c || '',
                NUA_Owner_Control__c: record.NUA_Owner_Control__c || '',
                VAS_TSPBRONZE__c: record.VAS_TSPBRONZE__c || '',
                VAS_TSPSOLV__c: record.VAS_TSPSOLV__c || '',
                VAS_TSPGULD__c: record.VAS_TSPGULD__c || '',
                Billing_Account__c: record.Billing_Account__c || '',
                Billing_Account_Number__c: record.Billing_Account_Number__c || '',
                Invoice_Type_F__c: record.Invoice_Type_F__c || '',
                Invoice_Email_F__c: record.Invoice_Email_F__c || '',
                Company_Name__c: record.Company_Name__c || '',
                EAN_number_F__c: record.EAN_number_F__c || '',
                Delivery_Att__c: record.Delivery_Att__c || '',
                Billing_Att_F__c: record.Billing_Att_F__c || '',
                Delivery_Street_and_number__c: record.Delivery_Street_and_number__c || '',
                Billing_Name_F__c: record.Billing_Name_F__c || '',
                Delivery_City__c: record.Delivery_City__c || '',
                Billing_Street_and_No_F__c: record.Billing_Street_and_No_F__c || '',
                Postal_Code__c: record.Postal_Code__c || '',
                Billing_Postal_Code_F__c: record.Billing_Postal_Code_F__c || '',
                Delivery_Country__c: record.Delivery_Country__c || '',
                Billing_City_F__c: record.Billing_City_F__c || '',
                Delivery_Email__c: record.Delivery_Email__c || '',
                Billing_Country_F__c: record.Billing_Country_F__c || ''
            }));

            const schema = [
                {
                    sheet: 'Activation lines',
                    columns: [
    { column: 'Product', type: String, value: (row) => row.Product__c },
    { column: 'Quote line', type: String, value: (row) => row.Quote_line__c },
    { column: 'Fixed no.', type: String, value: (row) => row.Phone_no__c },
    { column: 'First name', type: String, value: (row) => row.First_name__c },
    { column: 'Last name', type: String, value: (row) => row.Last_name__c },
    { column: 'Phone no Status', type: String, value: (row) => row.Phone_no_Status__c },
    { column: 'Mobile no.', type: String, value: (row) => row.Mobile_no__c },
    { column: 'Telia INSIGHT e-mail contact', type: String, value: (row) => row.Telia_INSIGHT_e_mail_contact__c },
    { column: 'SIM Number', type: String, value: (row) => row.SIM_number__c },
    { column: "Don't send to Activation", type: String, value: (row) => row.Not_to_Activation__c },
    { column: 'Operator', type: String, value: (row) => row.Operator__c },
    { column: 'Sales type', type: String, value: (row) => row.Sales_type__c },
    { column: 'Power of Attorney record', type: String, value: (row) => row.Power_of_Attorney_record__c },
    { column: 'Activation Planned delivery date', type: String, value: (row) => row.Planned_delivery_date__c },
    { column: 'Activation/Porting/Termination date', type: String, value: (row) => row.Number_Porting_Specific_Date__c },
    { column: 'Modified delivery date', type: String, value: (row) => row.Modified_delivery_date__c },
    { column: 'Number Porting End of Commitement', type: String, value: (row) => row.Number_Porting_End_of_Commitment__c },
    { column: 'Existing SIM Number', type: String, value: (row) => row.Existing_SIM_number__c },
    { column: 'Related Activation line', type: String, value: (row) => row.Related_Activation_line__c },
    { column: 'Telia til Telia transfer', type: String, value: (row) => row.Telia_til_Telia_transfer__c },
    { column: 'UC Invoicing', type: String, value: (row) => row.UC_Invoicing__c },
    { column: 'Number Series Main Number', type: String, value: (row) => row.Number_Series_Main_Number__c },
    { column: 'Show On Onboarding Page', type: String, value: (row) => row.Show_On_Onboarding_Page__c },
    { column: 'Onboarding  Activation Line', type: String, value: (row) => row.Onboarding_Activation_Line__c },
    { column: 'Escalated', type: String, value: (row) => row.Escalated__c },
    { column: 'Corporate 1 times tale DK til EU', type: String, value: (row) => row.VAS_CORDKTEU4__c },
    { column: 'Ekstra SIM-kort BtB', type: String, value: (row) => row.VAS_SIMBTB11__c },
    { column: 'Corporate 10 timers tale DK til EU', type: String, value: (row) => row.VAS_CORDKTEU5__c },
    { column: 'Ekstra Data SIM number', type: String, value: (row) => row.Ekstra_Data_SIM_number__c },
    { column: 'Corporate Fri tale DK til EU', type: String, value: (row) => row.VAS_CORDKTOEU__c },
    { column: 'Ekstra datakort – nummer 2', type: String, value: (row) => row.VAS_SIMBX5__c },
    { column: 'Telia Roaming World 5 GB', type: String, value: (row) => row.VAS_CORWA10G__c },
    { column: 'Ekstra Data SIM number 2', type: String, value: (row) => row.Ekstra_Data_SIM_number_2__c },
    { column: 'Telia Roaming World 20 GB', type: String, value: (row) => row.VAS_CORWA5G__c },
    { column: 'Ekstra datakort – nummer 3', type: String, value: (row) => row.VAS_SIMBX6__c },
    { column: 'Telia Roaming World Extra 20 GB', type: String, value: (row) => row.VAS_CORWB8G__c },
    { column: 'Ekstra Data SIM number 3', type: String, value: (row) => row.Ekstra_Data_SIM_number_3__c },
    { column: 'Telia Roaming World Flex 20 GB', type: String, value: (row) => row.VAS_CORWA9G__c },
    { column: 'Ekstra datakort – nummer 4', type: String, value: (row) => row.VAS_SIMBX7__c },
    { column: 'Roaming USA', type: String, value: (row) => row.VAS_CORUSA5G__c },
    { column: 'Ekstra Data SIM number 4', type: String, value: (row) => row.Ekstra_Data_SIM_number_4__c },
    { column: 'Roaming Asia', type: String, value: (row) => row.VAS_CORAS5G__c },
    { column: 'Corporate APN Bruger', type: String, value: (row) => row.VAS_DUMMY2__c },
    { column: 'Mobile status', type: String, value: (row) => row.VAS_ALLBIZA__c },
    { column: 'Telia Managed Service Bredbånd', type: String, value: (row) => row.VAS_TMSBBAND__c },
    { column: 'F2M Fixed to mobile', type: String, value: (row) => row.VAS_FIX2MOBIL__c },
    { column: 'Telia Managed Service', type: String, value: (row) => row.VAS_TMSMOBILE__c },
    { column: 'Telia Nummerdeling - teknisk produkt', type: String, value: (row) => row.VAS_EntitleAW__c },
    { column: 'M2M Roaming', type: String, value: (row) => row.VAS_M2MROAM__c },
    { column: 'M2M Data Pakke', type: String, value: (row) => row.VAS_M2M_Data__c },
    { column: 'M2M SMS Pakke', type: String, value: (row) => row.VAS_M2M_SMS__c },
    { column: 'Numbertype', type: String, value: (row) => row.Funktionsnr__c },
    { column: 'Touchpoint Statistik', type: String, value: (row) => row.Touchpoint_Statistik__c },
    { column: 'Touchpoint Bruger', type: String, value: (row) => row.Touchpoint_Bruger__c },
    { column: 'Touchpoint Softphone', type: String, value: (row) => row.Touchpoint_Softphone__c },
    { column: 'Touchpoint Receptionist', type: String, value: (row) => row.Touchpoint_Receptionist__c },
    { column: 'UC License', type: String, value: (row) => row.VAS_UC_License__c },
    { column: 'Email', type: String, value: (row) => row.Email__c },
    { column: 'Shortnr', type: String, value: (row) => row.Shortnr__c },
    { column: 'Department', type: String, value: (row) => row.Department__c },
    { column: 'Administrator', type: String, value: (row) => row.Administrator__c },
    { column: 'Job description', type: String, value: (row) => row.Job_description__c },
    { column: 'Supervisor', type: String, value: (row) => row.Supervisor__c },
    { column: 'Locale', type: String, value: (row) => row.Locale__c },
    { column: 'Attendant Agent login', type: String, value: (row) => row.Attendant_Agent_login__c },
    { column: 'Keywords', type: String, value: (row) => row.Keywords__c },
    { column: 'TPX Call Recording Basic', type: String, value: (row) => row.VAS_TPXRECB__c },
    { column: 'TPX Call Recording  3 years', type: String, value: (row) => row.VAS_TPXREC3__c },
    { column: 'TPX Call Recording 7 years', type: String, value: (row) => row.VAS_TPXREC7__c },
    { column: 'Fastnet no Type', type: String, value: (row) => row.Fastnet_no_Type__c },
    { column: 'Wallboard', type: String, value: (row) => row.Wallboard__c },
    { column: 'Fax', type: String, value: (row) => row.Fax__c },
    { column: 'Conference', type: String, value: (row) => row.Conference__c },
    { column: 'Extra ACD queue', type: String, value: (row) => row.Extra_ACD_k__c },
    { column: 'UC Statistics', type: String, value: (row) => row.Statistics__c },
    { column: 'Extra ACD queue Quantity', type: String, value: (row) => row.Extra_ACD_k_Quantity__c },
    { column: 'Single No.', type: String, value: (row) => row.Single_No__c },
    { column: 'Supervisor No.', type: String, value: (row) => row.Supervisor_No__c },
    { column: '70/80 nummer', type: String, value: (row) => row.X70_80_nummer__c },
    { column: 'Attendant Agent login No.', type: String, value: (row) => row.Attendant_Agent_login_No__c },
    { column: 'TPX Deskphone', type: String, value: (row) => row.TPX_Deskphone__c },
    { column: 'TPX Power Adapter', type: String, value: (row) => row.TPX_Power_Adapter__c },
    { column: 'MS Teams Phone Mobile', type: String, value: (row) => row.VAS_OCMUSR__c },
    { column: 'Fri tale til EU', type: String, value: (row) => row.VAS_FINTDKEU__c },
    { column: 'Attendant Console samtidige brugere', type: String, value: (row) => row.VAS_OCCATTCON__c },
    { column: 'Onboarding', type: String, value: (row) => row.VAS_OCCONB__c },
    { column: 'Office-klient; inkl. Activity Management', type: String, value: (row) => row.VAS_OCCOFFCLI__c },
    { column: 'Agent & Attendant Basic - Online', type: String, value: (row) => row.VAS_OCCAAO__c },
    { column: 'Contact Center Entprse - tale, samtidige', type: String, value: (row) => row.VAS_OCCCCENTV__c },
    { column: 'Agent & Attendant Start up - Online', type: String, value: (row) => row.VAS_OCCAAS__c },
    { column: 'Contact Center Workgroup - tale navngivn', type: String, value: (row) => row.VAS_OCCCCWGRV__c },
    { column: 'Agent & Attendant Opdatering - Online', type: String, value: (row) => row.VAS_OCCAAU__c },
    { column: 'Mobiliy Presence Gateway, per mobilbrug', type: String, value: (row) => row.VAS_OCCMOBPGW__c },
    { column: 'Admin Basic - Online', type: String, value: (row) => row.VAS_OCCBAS__c },
    { column: 'IVR Express, per hovednummer', type: String, value: (row) => row.VAS_OCCIVREXP__c },
    { column: 'Admin Statistik - Online', type: String, value: (row) => row.VAS_OCCASO__c },
    { column: 'Call Back, per kø', type: String, value: (row) => row.VAS_OCCCLBACK__c },
    { column: 'Konsulent, timepris', type: String, value: (row) => row.VAS_OCCCON__c },
    { column: 'Quality Monitor Wall Board, per bruger', type: String, value: (row) => row.VAS_OCCQUAMON__c },
    { column: 'Installation, konfiguration og test; per', type: String, value: (row) => row.VAS_OCCINS__c },
    { column: 'Contact Center Enterprise multichannel', type: String, value: (row) => row.VAS_OCCCCENTM__c },
    { column: 'Contact Center Workgroup - multichannel', type: String, value: (row) => row.VAS_OCCCCWGRM__c },
    { column: 'CRM Integrations-gateway, per agent', type: String, value: (row) => row.VAS_OCCCRMINT__c },
    { column: 'Mail distribution AC/CCE attendant/agent', type: String, value: (row) => row.VAS_OCCMAILDI__c },
    { column: 'Tilgængelighed taleagent/Office-klient', type: String, value: (row) => row.VAS_OCCAVAIVA__c },
    { column: 'Scheduled Statistics - per system/tenant', type: String, value: (row) => row.VAS_OCCSCSTAT__c },
    { column: 'Agent Recording - per AC/CCE agent', type: String, value: (row) => row.VAS_OCCAGRECO__c },
    { column: 'Barring 3G settings', type: String, value: (row) => row.VAS_BAR3G__c },
    { column: 'Spær indholdstakseret SMS', type: String, value: (row) => row.VAS_BARPRCSMS__c },
    { column: 'Barring 4G settings', type: String, value: (row) => row.VAS_BAR4G__c },
    { column: 'Spær opkald til 90 numre', type: String, value: (row) => row.VAS_BAR90__c },
    { column: 'Barring data services', type: String, value: (row) => row.VAS_BARDATA__c },
    { column: 'Spær udg. Fra udl. undt til', type: String, value: (row) => row.VAS_BARORXD__c },
    { column: 'Barring International Roaming', type: String, value: (row) => row.VAS_BARINTRO__c },
    { column: 'Spær udg. opkald fra udlandet', type: String, value: (row) => row.VAS_BAROUTRO__c },
    { column: 'Barring MMS', type: String, value: (row) => row.VAS_BARMMS__c },
    { column: 'Spær udg. opkald til int. nr', type: String, value: (row) => row.VAS_BARINTCAL__c },
    { column: 'Barring National & Intl roamin', type: String, value: (row) => row.VAS_BARTOTRO__c },
    { column: 'Standard GSM Barring', type: String, value: (row) => row.VAS_BARSTD__c },
    { column: 'Forbrugskontrol', type: String, value: (row) => row.VAS_BARLEVEL__c },
    { column: 'Forbrugskontrol amount', type: String, value: (row) => row.Forbrugskontrol_amount__c },
    { column: 'Spær alle indgående opkald', type: String, value: (row) => row.VAS_BARINC__c },
    { column: 'Total Barring of outgoing call', type: String, value: (row) => row.VAS_BARTOTAL__c },
    { column: 'Spær alle udgående opkald', type: String, value: (row) => row.VAS_BAROUTG__c },
    { column: 'RCC Owner Control', type: String, value: (row) => row.RCC_Owner_Control__c },
    { column: 'Spær indg. opkald i udlandet', type: String, value: (row) => row.VAS_BARINCRO__c },
    { column: 'TSRR Owner Control', type: String, value: (row) => row.TSRR_Owner_Control__c },
    { column: 'NUA Owner Control', type: String, value: (row) => row.NUA_Owner_Control__c },
    { column: 'Insight Premium Bronze', type: String, value: (row) => row.VAS_TSPBRONZE__c },
    { column: 'Insight Premium Sølv', type: String, value: (row) => row.VAS_TSPSOLV__c },
    { column: 'Insight Premium Guld', type: String, value: (row) => row.VAS_TSPGULD__c },
    { column: 'Billing Account', type: String, value: (row) => row.Billing_Account__c },
    { column: 'Billing Account Number', type: String, value: (row) => row.Billing_Account_Number__c },
    { column: 'Invoice Type', type: String, value: (row) => row.Invoice_Type_F__c },
    { column: 'Invoice Email', type: String, value: (row) => row.Invoice_Email_F__c },
    { column: 'Company Name', type: String, value: (row) => row.Company_Name__c },
    { column: 'EAN Number', type: String, value: (row) => row.EAN_number_F__c },
    { column: 'Delivery Att.', type: String, value: (row) => row.Delivery_Att__c },
    { column: 'Billing Att.', type: String, value: (row) => row.Billing_Att_F__c },
    { column: 'Delivery Street and number', type: String, value: (row) => row.Delivery_Street_and_number__c },
    { column: 'Billing Name', type: String, value: (row) => row.Billing_Name_F__c },
    { column: 'Delivery City', type: String, value: (row) => row.Delivery_City__c },
    { column: 'Billing Street and No', type: String, value: (row) => row.Billing_Street_and_No_F__c },
    { column: 'Postal Code', type: String, value: (row) => row.Postal_Code__c },
    { column: 'Billing Postal Code', type: String, value: (row) => row.Billing_Postal_Code_F__c },
    { column: 'Delivery Country', type: String, value: (row) => row.Delivery_Country__c },
    { column: 'Billing City', type: String, value: (row) => row.Billing_City_F__c },
    { column: 'Delivery Email', type: String, value: (row) => row.Delivery_Email__c },
    { column: 'Billing Country', type: String, value: (row) => row.Billing_Country_F__c }
]

                }
            ];

            const excelExport = this.template.querySelector('c-excel-export');
            if (excelExport) {
                excelExport.fields = this.fields;
                excelExport.recordId = this.recordId;
                excelExport.schema = schema;
                excelExport.fileName = this.objectApiName + '_' + this.caseNumber + '_ActivationLines.xlsx'; // File name for the export
                excelExport.exportData = this.activationLines;
                excelExport.invoke();
            } else {
                console.error('ExcelExport component not found.');
            }
        } catch (error) {
            this.showToast('Error', 'Failed to fetch Activation Lines.', 'error');
        }
    }

    showToast(title, message, variant) {
        this.dispatchEvent(new ShowToastEvent({ title, message, variant }));
    }
}