public with sharing class HomeOfficeConstants {
    
    public static final String AGREEMENT_TYPE_FRAMEWORK = 'Framework';
    public static final String AGREEMENT_TYPE_SPECIFIED = 'Specified'; 
    public static final String ERROR_MESSAGE_AGREEMENT_TYPE = 'Flow Action Error: Opportunity Agreement Type does not match neither ' + AGREEMENT_TYPE_FRAMEWORK + ' nor ' + AGREEMENT_TYPE_SPECIFIED;
    public static final String PRODUCTS_IN_SCOPE_HOME_OFFICE = 'Home Office';

    public static final String LOCATION_LINE_VAS_PRODUCT_FASTIP = 'FASTIP';

    public static final String LOCATION_LINE_SUBSCRIPTION_PRODUCT_DSLHOF01 = 'DSLHOF01';
    public static final String LOCATION_LINE_SUBSCRIPTION_PRODUCT_COAHOF03 = 'COAHOF03';
    public static final String LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF02 = 'FIBHOF02';  // (HomeOffice Fiber A 300 Mbit/s)
    public static final String LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF03 = 'FIBHOF03';  // (HomeOffice Fiber A 1000 Mbit/s)    
    public static final String LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF06 = 'FIBHOF06';
    public static final String LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF09 = 'FIBHOF09';
    public static final String LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF15 = 'FIBHOF15';

    public static final String LOCATION_LINE_OTC_PRODUCT_CHXT01 = 'CHXT01';
    public static final String LOCATION_LINE_OTC_PRODUCT_CHXT02 = 'CHXT02';
    public static final String LOCATION_LINE_OTC_PRODUCT_CHXT03 = 'CHXT03';
    public static final String LOCATION_LINE_OTC_PRODUCT_CHXT04 = 'CHXT04';
    public static final String LOCATION_LINE_OTC_PRODUCT_CHXT05 = 'CHXT05';
    public static final String LOCATION_LINE_OTC_PRODUCT_CHXT06 = 'CHXT06';
    public static final String LOCATION_LINE_OTC_PRODUCT_CHXT07 = 'CHXT07';
    public static final String LOCATION_LINE_OTC_PRODUCT_CHXT08 = 'CHXT08';
    public static final String LOCATION_LINE_OTC_PRODUCT_CHXT11 = 'CHXT11';
    public static final String LOCATION_LINE_OTC_PRODUCT_CHXT12 = 'CHXT12';
}